# Use node:lts-alpine as base image
FROM node:lts-alpine as base

# Update and install bash
RUN apk update && apk upgrade && apk add --no-cache bash

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy the rest of the application code
COPY . .

RUN chown -R node:node /app

# Switch to non-root user
USER node

RUN yarn build