services:
    # Database service
    postgres-db:
        container_name: postgres-db
        image: postgres:latest
        restart: always
        env_file:
            - ./backend/.env
        ports:
            - "5432:5432"
        volumes:
            - ./backend/postgres:/var/lib/postgresql/data

    # Redis service
    redis:
        container_name: redis
        image: redis:latest
        command: ["redis-server", "--requirepass", "password"]
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

    # Backend API service
    api:
        container_name: api
        build:
            context: ./backend
            dockerfile: Dockerfile.local
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./backend:/app:z
        env_file:
            - ./backend/.env
        restart: always
        depends_on:
            - postgres-db
            - redis
        command: ["/bin/bash", "/app/scripts/entrypoint.local.sh"]

    # Frontend service
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - /app/node_modules
            - ./frontend:/app:z
        env_file:
            - ./frontend/.env
        command: "yarn dev --host 0.0.0.0"
        restart: always
        depends_on:
            - api

volumes:
    redis-data:
